--================>>>>>>>> QUERY RESULT--1

WITH CRSR AS
(
SELECT *,ROW_NUMBER() OVER (PARTITION BY EMPID, EMPNAME, SALARY, DOB ORDER BY EMPID, EMPNAME, SALARY, DOB) AS RN
FROM [HEALTHCUREGUIDE].[dbo].[EMPLOYEE]
)
DELETE FROM CRSR WHERE RN<>1;

-->>> IT WILL REMOVE LAST RECORD (ADDED IN LAST)


--================>>>>>>>> QUERY RESULT--2
IF EXISTS (SELECT TOP 1 * FROM [dbo].[REGION])
BEGIN
  DROP TABLE [dbo].[REGION]
END
-->> QUERY WILL BE EXECUTED SUCCESSFULLY SINCE NULL VALUE ROW EXISTS.
-->> TABLE WILL NOT BE DROPPED


-->> TO DROP TABLE, CORRECT STATEMENT WOULD BE:
IF NOT EXISTS (SELECT TOP 1 * FROM [dbo].[REGION])
BEGIN
  DROP TABLE [dbo].[REGION]
END

--================>>>>>>>> QUERY RESULT--3

-->> SIMPLE BUT .... PERFORMANCE MAY BE A ISSUE DUE TO NESTED QUERY
SELECT E.EMPID, E.EMPNAME
FROM [dbo].[EMPLOYEE] E
WHERE E.DEPTID NOT IN (SELECT D.DEPTID FROM [dbo].[DEPARTMENT] D);